'use client';
import Link from "next/link";
import {useEffect,useRef,useState} from 'react';
import {MapPin,Trash2,Plus,Bookmark,CalendarDays,Sparkles,Footprints} from 'lucide-react';
import {useCityCollection} from '@/hooks/use-city-collection';
import {useEventFeed} from '@/hooks/use-event-feed';
import {themes,venueFor,nearbyLandmarks,timeLabel,dateLabel,type CultureEvent} from '@/lib/events/model';
import {buildTimeline,validateSelection,suggestEvents,startPoints,type PlanWindow,type DayPlan} from '@/lib/events/planner';
import {walkingDirectionsUrl} from '@/lib/maps';
import {exportTimeline} from '@/lib/events/calendar-export';
import {RouteMap} from './route-map';
import {restoreDraftSettings} from '@/lib/events/draft-settings';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export function DayPlanner(){
 const {data,ready,error:storageError,update}=useCityCollection();const {feed,loading,error,reload}=useEventFeed();
 const [landmarkIds,setLandmarkIds]=useState<string[]>([]),[before,setBefore]=useState(60),[maxKm,setMaxKm]=useState(3),[title,setTitle]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<string|null>(null);const loaded=useRef(false);const [originId,setOriginId]=useState(''),[startClock,setStartClock]=useState(''),[endClock,setEndClock]=useState('23:00'),[placement,setPlacement]=useState<PlanWindow['placement']>('both'),[suggestionLimit,setSuggestionLimit]=useState(6);const [settingsReady,setSettingsReady]=useState(false);
 useEffect(()=>{
  if(!ready||loaded.current)return;loaded.current=true;
  const id=new URLSearchParams(window.location.search).get('plan');
  const plan=id?data.plans.find(p=>p.id===id):undefined;
  if(id&&!plan)setNotice('Bu cihazda bu plan bulunamadı.');
  if(plan){update(s=>({...s,draft:plan.events,theme:plan.theme}));setTitle(plan.title);setLandmarkIds(plan.landmarkIds);setBefore(plan.beforeMinutes??60);setMaxKm(plan.maxKm??3);setEditing(plan.id);if(plan.window){setOriginId(plan.window.originId);setStartClock(timeLabel(plan.window.start));setEndClock(timeLabel(plan.window.end));setPlacement(plan.window.placement);}}
  else {const first=[...data.draft].sort((a,b)=>a.start.localeCompare(b.start))[0];const saved=restoreDraftSettings(data.draftSettings,first?.start.slice(0,10)??'');if(saved){setTitle(saved.title);setLandmarkIds(saved.landmarkIds);setBefore(saved.before);setMaxKm(saved.maxKm);setEditing(saved.editing);setOriginId(saved.originId);setStartClock(saved.startClock);setEndClock(saved.endClock);setPlacement(saved.placement);}}
  setSettingsReady(true);
 },[ready]);
 const selected=[...data.draft].sort((a,b)=>a.start.localeCompare(b.start));const first=selected[0];
 const date=first?.start.slice(0,10)??'';const defaultStart=first?Math.max(Date.parse(date+'T00:00:00+03:00'),Date.parse(first.start)-before*60000):0;const planningWindow:PlanWindow={originId:originId||'venue:'+(first?.event.venueId??''),start:date+'T'+(startClock||(first?timeLabel(new Date(defaultStart).toISOString()):'12:00'))+':00+03:00',end:date+'T'+endClock+':00+03:00',placement};
 useEffect(()=>{if(!ready||!settingsReady||storageError)return;update(s=>({...s,draftSettings:{date,title,landmarkIds,before,maxKm,originId,startClock,endClock,placement,editing}}));},[ready,settingsReady,storageError,date,title,landmarkIds,before,maxKm,originId,startClock,endClock,placement,editing]);
 const sourceErrors=!loading&&feed?selected.filter(item=>!feed.events.some(e=>e.id===item.event.id)&&!feed.sources?.find(s=>s.id===item.event.sourceId)?.error).map(item=>`${item.event.title}: son kaynak listesinde bulunamadı. Resmî bağlantıyı kontrol edip etkinliği yeniden seç.`):[];
 const errors=selected.length?[...validateSelection(selected,maxKm,planningWindow),...sourceErrors]:[];
 const result=buildTimeline(selected,landmarkIds,before,planningWindow,maxKm);
 const routeStops=result.timeline.flatMap(s=>s.stop?[s.stop]:[]);const directions=walkingDirectionsUrl(routeStops);
 const nearby=[...new Map(selected.flatMap(item=>nearbyLandmarks(item.event,data.theme,maxKm).map(rec=>[rec.stop.id,rec] as const))).values()].sort((a,b)=>Number(b.match)-Number(a.match)||a.km-b.km);
 const suggestions=suggestEvents(feed?.events??[],selected,data.theme,maxKm,planningWindow);
 const walkTotal=result.timeline.reduce((sum,item)=>sum+(item.walkAfter??0),0);
 function applySuggestions(){
  const trial=buildTimeline(selected,[...new Set([...landmarkIds,...nearby.map(r=>r.stop.id)])],before,planningWindow,maxKm);
  const fits=trial.timeline.filter(i=>i.kind==='landmark').map(i=>i.id);
  const added=fits.filter(id=>!landmarkIds.includes(id));
  setLandmarkIds(ids=>[...new Set([...ids,...added])]);
  setNotice(added.length?`${added.length} uygun mola gününe eklendi. Akıştan saatlerini kontrol edebilirsin.`:'Şu an zamanına sığan yeni bir mola yok. İlk etkinlik öncesi süreyi artırabilirsin.');
 }
 function patch(id:string,fields:{start?:string;duration?:number}){update(s=>({...s,draft:s.draft.map(i=>i.event.id===id?{...i,...fields}:i)}));setNotice('');}
 function add(event:CultureEvent,start=event.startsAt,duration=event.category==='Film'?120:90){if(data.draft.length>=6){setNotice('Bir günlük plana en fazla 6 etkinlik eklenebilir.');return;}if(validateSelection([...selected,{event,start,duration}],maxKm,planningWindow).length){setNotice('Bu öneri mevcut plana artık sığmıyor. Saatleri ve süreleri kontrol et.');return;}setOriginId(planningWindow.originId);setStartClock(timeLabel(planningWindow.start));if(update(s=>({...s,draft:[...s.draft,{event,start,duration}]})))setNotice('Etkinlik gününe eklendi. Akışta yerini görebilirsin.');}
 function save(){if(errors.length||!selected.length||loading||!feed){setNotice('Kaydetmeden önce plan uyarılarını çöz ve kaynak kontrolünün bitmesini bekle.');return;}const plan:DayPlan={id:editing??crypto.randomUUID(),title:title.trim()||themes.find(t=>t.id===data.theme)?.name+' · '+dateLabel(first.start),theme:data.theme,date:first.start.slice(0,10),events:selected,landmarkIds,beforeMinutes:before,maxKm,window:planningWindow,createdAt:new Date().toISOString()};if(update(s=>({...s,plans:[plan,...s.plans.filter(p=>p.id!==plan.id)].slice(0,30)}))){setEditing(plan.id);setNotice('Plan bu cihazda kaydedildi. Rotalarım sayfasından tekrar açabilirsin.');}}
 return <main className="day-planner"><div className="culture-heading"><div><span className="eyebrow">ETKİNLİKTEN ŞEHİR ROTASINA</span><h1>Bir gün, senin İstanbul’un.</h1><p className="planner-intro">Etkinliklerini seç, yakın keşiflerle birleştir. Geriye günün keyfini çıkarmak kalsın.</p></div><div className="planner-heading-links"><Link className="plan-link" href="/my-routes">Rotalarım ({data.plans.length})</Link><Link className="plan-link" href="/">Etkinlik ekle <Plus size={17}/></Link></div></div>
  {!ready&&<p>Planın yükleniyor…</p>}{storageError&&<p role="alert" className="agenda-notice">{storageError}</p>}
  <p className="draft-save-status">{ready&&!storageError?'Taslak ve ayarların bu cihazda otomatik saklanır.':''}</p><nav className="planner-steps" aria-label="Rota oluşturma adımları"><a href={selected.length?'#plan-settings':'/'}><span>01</span>Etkinlik & konsept</a><a href={selected.length?'#plan-discoveries':'/'}><span>02</span>Yakın keşifler</a><a href={selected.length?'#plan-preview':'/'}><span>03</span>Günün rotası</a></nav>
  {!selected.length?<div className="planner-empty"><CalendarDays size={32}/><h2>Bir etkinlikle başla.</h2><p>Aynı gün yakın mekânlardaki etkinlikleri seç; çevresine kısa kültür durakları ekle.</p><Link className="plan-primary" href="/">Etkinlikleri keşfet</Link></div>:<>
  <section className="planner-settings planner-core-settings" id="plan-settings"><label>Plan adı<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} placeholder="Örneğin: Kadıköy’de edebiyat günü"/></label><label>Konsept<select value={data.theme} onChange={e=>update(s=>({...s,theme:e.target.value}))}>{themes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><details className="planner-fine-tune"><summary>Mesafe ve hızlı başlangıç ayarları</summary><div><label>Hızlı başlangıç aralığı<select value={before} onChange={e=>{setBefore(Number(e.target.value));setStartClock('');}}><option value={30}>30 dakika</option><option value={60}>1 saat</option><option value={120}>2 saat</option></select></label><label>Mekânlar arası yakınlık<select value={maxKm} onChange={e=>setMaxKm(Number(e.target.value))}><option value={1}>En fazla 1 km</option><option value={3}>En fazla 3 km</option><option value={5}>En fazla 5 km</option></select></label></div></details></section>
  <section className="planner-journey"><div><span className="planner-step-label">YOLA NEREDEN, NE ZAMAN ÇIKIYORSUN?</span><h2>Günün sınırlarını belirle</h2><p>Başlangıç noktasında bulunacağın saati seç. Öneriler bu saatten başlayıp bitiş saatine kadar hesaplanır.</p></div><div className="journey-fields"><label>Başlangıç noktası<select value={planningWindow.originId} onChange={e=>setOriginId(e.target.value)}><optgroup label="Etkinlik mekânları">{startPoints.filter(p=>p.id.startsWith('venue:')).map(p=><option key={p.id} value={p.id}>{p.name} · {p.area}</option>)}</optgroup><optgroup label="Şehir durakları">{startPoints.filter(p=>p.id.startsWith('landmark:')).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</optgroup></select></label><label>Yola çıkış saati<input type="time" value={timeLabel(planningWindow.start)} onChange={e=>setStartClock(e.target.value)}/></label><label>Günü bitirme saati<input type="time" value={endClock} onChange={e=>setEndClock(e.target.value)}/></label><label>Hangi bölüme öneri istersin?<select value={placement} onChange={e=>setPlacement(e.target.value as PlanWindow['placement'])}><option value="both">Öncesi ve sonrası</option><option value="before">İlk etkinlik öncesi</option><option value="after">Son etkinlik sonrası</option></select></label></div><small>Yaya rotasıdır; farklı yakalara geçiş veya toplu taşıma süresi hesaplanmaz. Başlangıç ve saatler rotayla birlikte kaydedilir.</small></section>
  <div className="planner-layout"><div className="planner-editor"><section><div className="planner-section-title"><h2><small className="planner-step-label">01 / ANA DURAKLAR</small>Seçtiğin etkinlikler <span>{selected.length}</span></h2><AlertDialog><AlertDialogTrigger asChild><button type="button">Taslağı temizle</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Gün taslağını temizleyelim mi?</AlertDialogTitle><AlertDialogDescription>Seçtiğin etkinlikler ve mola ayarları temizlenir. Kaydettiğin rotalar korunur.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction onClick={()=>{update(s=>({...s,draft:[],draftSettings:undefined}));setEditing(null);setLandmarkIds([]);setTitle('');setOriginId('');setStartClock('');setEndClock('23:00');setPlacement('both');}}>Taslağı temizle</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><p className="planner-help">Süre, etkinlik için ayırdığın zamandır. Kaynakta bitiş saati olmadığında gerçek süreyi resmî sayfadan kontrol et.</p>
  {selected.map(item=>{const event=item.event,venue=venueFor(event);return <article className="planned-event" key={event.id}><div><span className="event-tag">{event.category} · {event.festival}</span><h3><a href={'/events/'+encodeURIComponent(event.id)}>{event.title}</a></h3><p><MapPin size={14}/>{event.venueName??venue?.name??'Konum doğrulanmadı'}</p></div><button className="remove-event" aria-label={event.title+' etkinliğini kaldır'} onClick={()=>update(s=>({...s,draft:s.draft.filter(i=>i.event.id!==event.id)}))}><Trash2 size={17}/></button><div className="planned-event-inputs">{event.timeKnown===false?<><label>Ziyaret tarihi<input type="date" value={item.start.slice(0,10)} min={event.startsAt.slice(0,10)} max={event.endsAt?.slice(0,10)??event.startsAt.slice(0,10)} onChange={e=>{if(e.target.value)patch(event.id,{start:e.target.value+'T'+item.start.slice(11,16)+':00+03:00'});}}/></label><label>Ziyaret saati<input type="time" value={item.start.slice(11,16)} onChange={e=>{if(e.target.value)patch(event.id,{start:item.start.slice(0,10)+'T'+e.target.value+':00+03:00'});}}/></label></>:<div className="fixed-start"><strong>{dateLabel(item.start)}</strong><span>{timeLabel(item.start)} · Resmî başlangıç</span></div>}<label>Ayırdığın süre (dk)<input type="number" min={15} max={480} step={15} value={item.duration} onChange={e=>patch(event.id,{duration:Number(e.target.value)})}/></label><a href={event.sourceUrl} target="_blank" rel="noreferrer">Resmî etkinlik</a></div></article>;})}</section>
  <section className="planner-recommendations" id="plan-discoveries"><div className="planner-section-title"><h2><small className="planner-step-label">02 / YAKIN KEŞİFLER</small>Gitmişken uğra</h2>{nearby.length>0&&<button className="suggest-stops" onClick={applySuggestions} disabled={!!errors.length||loading}><Sparkles size={16}/>Uygun molaları ekle</button>}</div><p className="planner-help">Konseptine uygun, yakın açık hava durakları. Seçtiğin duraklar zamanına sığarsa plana eklenir.</p>{nearby.length?nearby.map(({stop,km,match})=><label className="landmark-choice" key={stop.id}><input type="checkbox" checked={landmarkIds.includes(stop.id)} onChange={e=>setLandmarkIds(ids=>e.target.checked?[...ids,stop.id]:ids.filter(id=>id!==stop.id))}/><div>{stop.photo&&<img className="landmark-choice-photo" src={stop.photo} alt={stop.name} loading="lazy"/>}<strong>{stop.name}</strong><small>Yaklaşık {km.toFixed(1)} km · 15 dk mola{match?' · Konseptine uygun':''}</small><p>{stop.tip}</p>{stop.photoCredit&&<small className="landmark-credit">Fotoğraf: <a href={stop.photoCredit.source} target="_blank" rel="noreferrer">{stop.photoCredit.name}</a> · {stop.photoCredit.license} · boyutlandırıldı</small>}</div></label>):<p>Bu mekânlar çevresinde doğrulanmış kısa durak önerisi henüz yok.</p>}</section>
  <section className="planner-recommendations real-event-recommendations"><span className="planner-step-label">RESMÎ PROGRAMDAN · GÜNÜNE UYGUN</span><h2>Etkinliğin öncesi ve sonrası</h2><p className="planner-help">Başlangıcına, saat aralığına ve yürüyüş mesafene sığan gerçek etkinlikler. Saat belirtilmeyen sergi ve ziyaretlerde önerilen saat, resmî başlangıç değildir.</p>{loading?<p>Güncel etkinlikler taranıyor…</p>:!suggestions.length?<p className="suggestion-empty">Bu koşullarda uygun etkinlik bulunamadı. Başlangıcı erkene alabilir, günü uzatabilir veya yakınlık sınırını artırabilirsin.</p>:['before','between','after'].map(slot=>{const group=suggestions.filter(s=>s.slot===slot);return group.length?<div className="suggestion-group" key={slot}><h3>{slot==='before'?'Etkinlik öncesi':slot==='after'?'Etkinlik sonrası':'Etkinliklerin arasında'} <span>{group.length}</span></h3>{group.slice(0,suggestionLimit).map(rec=><article className="suggested-event" key={rec.event.id}><div><span className="event-tag">{rec.event.category} · {rec.match?'Konseptine uygun':rec.event.festival}</span><strong><a href={'/events/'+encodeURIComponent(rec.event.id)}>{rec.event.title}</a></strong><p>{timeLabel(rec.start)} · {rec.duration} dk ayır · {rec.event.timeKnown===false?'Önerilen ziyaret saati':'Resmî başlangıç'}</p><small>{venueFor(rec.event)?.name} · yaklaşık {rec.km.toFixed(1)} km</small></div><button onClick={()=>add(rec.event,rec.start,rec.duration)} disabled={selected.length>=6} aria-label={rec.event.title+' etkinliğini plana ekle'}><Plus size={16}/>Ekle</button></article>)}{group.length>suggestionLimit&&<button className="suggestion-more" onClick={()=>setSuggestionLimit(n=>n+6)}>Daha fazla öneri göster</button>}</div>:null;})}</section>
  </div><aside className="planner-preview" id="plan-preview"><span className="planner-step-label">03 / GÜNÜN ROTASI</span><h2>Günün akışı</h2>{first&&<p className="planner-date">{dateLabel(first.start)}</p>}<div className="planner-summary"><span><CalendarDays size={17}/><strong>{selected.length}</strong> etkinlik</span><span><MapPin size={17}/><strong>{result.timeline.filter(i=>i.kind==='landmark').length}</strong> mola</span>{!errors.length&&<span><Footprints size={17}/><strong>≈ {walkTotal}</strong> dk yürüyüş</span>}</div>{loading&&<p role="status">Güncel program kontrol ediliyor…</p>}{error&&<p role="alert">{error}<button onClick={()=>void reload()}>Tekrar dene</button></p>}{errors.length>0&&<div className="planner-warnings" role="alert"><strong>Planı düzenle</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}{feed?.stale&&<p className="agenda-notice">Bazı kaynaklar yenilenemedi. Etkinliğe gitmeden önce resmî programı kontrol et.</p>}
   {result.omitted.length>0&&<p className="agenda-notice">Zamana veya yakınlığa sığmayan duraklar: {result.omitted.join(', ')}.</p>}
   {!errors.length&&<><RouteMap stops={routeStops} className="planner-map"/><ol className="day-timeline">{result.timeline.map(item=><li key={item.id}><time>{timeLabel(item.start)}<small>{timeLabel(item.end)}</small></time><div><span>{item.kind==='origin'?'YOLA ÇIKIŞ':item.kind==='event'?'ETKİNLİK':'KÜLTÜR MOLASI'}</span><strong>{item.kind==='event'?<a href={'/events/'+encodeURIComponent(item.id)}>{item.name}</a>:item.name}</strong>{item.tip&&<p className="timeline-tip">{item.tip}</p>}<small>{item.kind==='origin'?'Başlangıç noktası':item.kind==='event'?'Ayırdığın süre: '+Math.round((Date.parse(item.end)-Date.parse(item.start))/60000)+' dk':'15 dk açık hava molası'}</small>{item.walkAfter!==undefined&&<small>Sonraki durağa yaklaşık {item.walkAfter} dk yürüyüş</small>}{item.idleAfter!==undefined&&<small className="timeline-free-time">{item.idleAfter} dk serbest zaman</small>}</div></li>)}</ol><p className="planner-help">Etkinliklere 15 dk erken varış payı ayrılır. Yürüyüş seçtiğin başlangıç noktasından hesaplanır; oraya ulaşım süren dahil değildir. Haritadaki çizgiler durak sırasını gösterir; gerçek yaya yolunu harita uygulamasından kontrol et.</p></>}
   <div className="planner-buttons"><button className="plan-primary" disabled={!!errors.length||loading||!feed} onClick={save}><Bookmark size={17}/>Planı kaydet</button>{!errors.length&&<><button onClick={()=>exportTimeline(result.timeline)}>Takvimime ekle</button>{directions&&<a href={directions} target="_blank" rel="noreferrer">Yürüyüş yolunu aç</a>}</>}</div><Link className="view-my-routes" href="/my-routes">Oluşturduğum rotaları gör</Link><small className="planner-help">Planlar ve ilgi alanları bu tarayıcıda saklanır.</small>{notice&&<p role="status" className="culture-notice">{notice}</p>}
  </aside></div></>}
 </main>;
}
