'use client';
import Link from "next/link";
import {useState} from 'react';
import {EventPoster} from '@/components/event-poster';
import {EventMonthCalendar} from '@/components/event-month-calendar';
import {sampleRoutes} from '@/lib/routes';
import {Bookmark,CalendarDays,MapPin,Plus,Check,SlidersHorizontal} from 'lucide-react';
import {useEventFeed} from '@/hooks/use-event-feed';
import {useCityCollection} from '@/hooks/use-city-collection';
import {categories,themes,activeOn,localDate,dateLabel,timeLabel,venueFor,type CultureEvent} from '@/lib/events/model';
export function EventWorkspace({mode='explore'}:{mode?:'explore'|'calendar'}){
 const {feed,loading,error,reload}=useEventFeed();const {data,ready,error:storageError,update}=useCityCollection();
 const [date,setDate]=useState(''),[category,setCategory]=useState('all'),[area,setArea]=useState('all'),[source,setSource]=useState('all'),[free,setFree]=useState(false),[query,setQuery]=useState(''),[forYou,setForYou]=useState(false),[limit,setLimit]=useState(40),[notice,setNotice]=useState('');
 const [now] = useState(() => new Date());
 const today=localDate(now);const tomorrow=localDate(new Date(now.getTime()+86400000));const cover=sampleRoutes[0];const calendarDate=date||today;
 const events=feed?.events??[];
 const areas=[...new Set(events.map(e=>venueFor(e)?.area).filter((s):s is string=>!!s))].sort((a,b)=>a.localeCompare(b,'tr'));
 const score=(e:CultureEvent)=>Number(data.interests.includes(e.category))*2+Number(themes.find(t=>t.id===data.theme)?.categories.some(c=>c===e.category));
 const matchingEvents=events.filter(e=>(category==='all'||category===e.category)&&(area==='all'||venueFor(e)?.area===area)&&(source==='all'||e.sourceId===source)&&(!free||e.free)&&(!query||(e.title+' '+e.festival+' '+(e.venueName??venueFor(e)?.name??'')+' '+(venueFor(e)?.area??'')).toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))));
 const filtered=matchingEvents.filter(e=>!(date||mode==='calendar')||activeOn(e,calendarDate)).sort((a,b)=>forYou?score(b)-score(a)||a.startsAt.localeCompare(b.startsAt):a.startsAt.localeCompare(b.startsAt));
 const activeFilters=Number(area!=='all')+Number(source!=='all')+Number(free)+Number(forYou);
 function resetFilters(){setCategory('all');setArea('all');setSource('all');setFree(false);setForYou(false);setQuery('');setDate(mode==='calendar'?today:'');setLimit(40);}
 function add(event:CultureEvent){
  if(data.draft.some(s=>s.event.id===event.id)){update(s=>({...s,draft:s.draft.filter(i=>i.event.id!==event.id)}));return;}
  if(data.draft.length>=6){setNotice('Bir günlük plana en fazla 6 etkinlik ekleyebilirsin.');return;}
  const start=event.timeKnown===false?(activeOn(event,calendarDate)?calendarDate:event.startsAt.slice(0,10))+'T14:00:00+03:00':event.startsAt;
  if(update(s=>({...s,draft:[...s.draft,{event,start,duration:event.category==='Film'?120:90}]})))setNotice(event.timeKnown===false?'Plana eklendi. Ziyaret saatini Planım sayfasında seçebilirsin.':'Plana eklendi.');
 }
 function bookmark(event:CultureEvent){update(s=>({...s,bookmarks:s.bookmarks.some(e=>e.id===event.id)?s.bookmarks.filter(e=>e.id!==event.id):[event,...s.bookmarks].slice(0,100)}));}
 return <main className="culture-workspace">
  <div className={'culture-heading discover-hero '+(mode==='calendar'?'calendar-hero':'')}><div><span className="eyebrow">İSTANBUL’UN KÜLTÜR GÜNDEMİ</span><h1>{mode==='calendar'?<>Şehrin <em>ritmini</em><br/>takip et.</>:<>Bir şehir.<br/><em>Bin ihtimal.</em></>}</h1><p>{mode==='calendar'?'Bir gün seç, programı keşfet, sana uygun rotayı kur.':'Bir film, bir sahne, hiç bilmediğin bir sokak. İstanbul’un kültür programından sana ait bir gün çıkar.'}</p><Link className="plan-link" href="/planner"><CalendarDays size={18}/>{data.draft.length?'Planına devam et':'Gününü tasarla'}{data.draft.length>0&&<b>{data.draft.length}</b>}</Link>{feed&&<small className="discover-feed-note">{events.length} güncel etkinlik ve seans · {feed.sources?.filter(s=>s.count>0).length??0} kaynak</small>}</div>{mode==='explore'&&<figure className="discover-photo"><img src={cover.cover} alt="Karaköy’ün sokakları"/><figcaption>İstanbul, adım adım · <a href={cover.coverCredit?.source} target="_blank" rel="noreferrer">{cover.coverCredit?.name} · {cover.coverCredit?.license}</a> · boyutlandırıldı</figcaption></figure>}</div>
  <section className="discover-controls" aria-label="Etkinlik filtreleri"><div className="discover-search-row"><label className="culture-search">Ne keşfetmek istersin?<input type="search" placeholder="Etkinlik, mekân veya semt ara…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40);}}/></label><label>Tarih<input type="date" value={mode==='calendar'?calendarDate:date} min={today} onChange={e=>{setDate(e.target.value);setLimit(40);}}/></label></div>{mode==='explore'&&<div className="quick-dates"><button aria-pressed={!date} onClick={()=>setDate('')}>Tüm tarihler</button><button aria-pressed={date===today} onClick={()=>setDate(today)}>Bugün</button><button aria-pressed={date===tomorrow} onClick={()=>setDate(tomorrow)}>Yarın</button></div>}
  <div className="culture-chips discover-categories"><button aria-pressed={category==='all'} onClick={()=>setCategory('all')}>Tümü</button>{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
  <details className="discover-refine"><summary><SlidersHorizontal size={16}/>Filtreler & kişiselleştirme{activeFilters>0&&<b>{activeFilters}</b>}</summary><div className="discover-refine-fields"><label>Semt<select value={area} onChange={e=>setArea(e.target.value)}><option value="all">Tüm semtler</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Kaynak<select value={source} onChange={e=>setSource(e.target.value)}><option value="all">Tüm kaynaklar</option>{feed?.sources?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="refine-check"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/>Yalnızca ücretsiz</label><label className="refine-check"><input type="checkbox" checked={forYou} onChange={e=>setForYou(e.target.checked)}/>İlgilerime göre sırala</label></div><section className="culture-personal" aria-label="İlgi alanları"><div><strong>İlgi alanların</strong><small>Bu cihazda saklanır.</small></div><div className="culture-chips">{categories.filter(c=>c!=='Diğer').map(c=><button key={c} disabled={!ready} aria-pressed={data.interests.includes(c)} onClick={()=>update(s=>({...s,interests:s.interests.includes(c)?s.interests.filter(x=>x!==c):[...s.interests,c]}))}>{c}</button>)}</div></section></details>
  </section>
  {mode==='calendar'&&<EventMonthCalendar date={calendarDate} today={today} events={matchingEvents} loading={loading} onSelect={day=>{setDate(day);setLimit(40);}}/>}
  <div className="culture-results-heading"><h2>{date||mode==='calendar'?dateLabel(calendarDate+'T12:00:00+03:00'):'Yaklaşan etkinlikler'} <span>{filtered.length}</span></h2>{(activeFilters>0||query||category!=='all'||date)&&<button onClick={resetFilters}>Seçimleri temizle</button>}</div>
  {loading&&<div className="event-loading" role="status"><span className="loading-dot"/>Güncel program hazırlanıyor…</div>}{error&&<p role="alert" className="agenda-notice">{error} <button onClick={()=>void reload()}>Tekrar dene</button></p>}{feed?.error&&<p role="alert" className="agenda-notice">{feed.error}</p>}{storageError&&<p role="alert" className="agenda-notice">{storageError}</p>}{notice&&<p role="status" className="culture-notice">{notice}</p>}
  {!loading&&!error&&!feed?.error&&!filtered.length&&<div className="agenda-empty"><CalendarDays size={30}/><p>Bu seçim için güncel etkinlik bulunamadı.</p><button onClick={resetFilters}>Filtreleri temizle</button></div>}
  <div className="culture-event-grid" aria-busy={loading}>{filtered.slice(0,limit).map((event,index)=>{const venue=venueFor(event),chosen=data.draft.some(i=>i.event.id===event.id),saved=data.bookmarks.some(e=>e.id===event.id);return <article className={'culture-event'+(chosen?' in-plan':'')} key={event.id}>{index<6&&<EventPoster event={event}/>}<div className="event-card-body"><div className="event-card-date"><strong>{Number(event.startsAt.slice(8,10))}</strong><span>{new Intl.DateTimeFormat('tr-TR',{month:'short',timeZone:'Europe/Istanbul'}).format(new Date(event.startsAt))}</span></div><div className="culture-event-top"><span className={'category-mark category-'+event.category}>{event.category}</span>{event.free&&<span className="free-mark">Ücretsiz</span>}<button aria-label={saved?'Kaydı kaldır':'Etkinliği kaydet'} aria-pressed={saved} disabled={!ready} onClick={()=>bookmark(event)}><Bookmark size={19} fill={saved?'currentColor':'none'}/></button></div><p className="event-source">{event.festival}</p><h3><a href={'/events/'+encodeURIComponent(event.id)}>{event.title}</a></h3>{event.director&&<p className="event-director">{event.director}</p>}<div className="event-when"><CalendarDays size={15}/><span>{dateLabel(event.startsAt)}{event.endsAt?' – '+dateLabel(event.endsAt):''}{event.timeKnown===false?' · Saat belirtilmemiş':' · '+timeLabel(event.startsAt)}</span></div><div className="event-where"><MapPin size={15}/><span>{event.venueName??venue?.name??'Mekân belirtilmemiş'}{venue?' · '+venue.area:''}</span></div>{forYou&&score(event)>0&&<small className="interest-match">Seçtiğin ilgi alanına uyuyor</small>}
   <div className="culture-event-actions"><button className="add-plan" disabled={!ready} onClick={()=>add(event)}>{chosen?<Check size={16}/>:<Plus size={16}/>}{chosen?'Planımda':'Plana ekle'}</button><a className="event-details-toggle" href={'/events/'+encodeURIComponent(event.id)}>Etkinliği incele</a></div></div>
  </article>;})}</div>
  {filtered.length>limit&&<button className="culture-load-more" onClick={()=>setLimit(limit+40)}>Daha fazla göster ({filtered.length-limit})</button>}
  <details className="culture-sources"><summary>Kaynaklar ve güncellik</summary><p>Takvim açıldığında kaynaklar en fazla altı saatte bir kontrol edilir. Passo kapsamı öne çıkan tarihli etkinliklerle sınırlıdır; İstanbul’daki tüm etkinlikleri kapsamaz.</p><div>{feed?.sources?.map(s=><article key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><span>{s.scope} · {s.count} yaklaşan etkinlik</span><small>{s.error??(s.checkedAt?'Son kontrol: '+dateLabel(s.checkedAt)+' '+timeLabel(s.checkedAt):'Kontrol bekleniyor')}{s.stale&&s.checkedAt?' · Eski kayıt':''}</small></article>)}</div></details>
  {data.draft.length>0&&<div className="culture-draft-bar"><span><strong>{data.draft.length} etkinlik</strong> seçtin</span><Link href="/planner">Gününü tasarla</Link></div>}
 <footer className="editorial-footer"><div><strong>City Curator</strong><p>İstanbul’u bir etkinlikten fazlasıyla keşfet. Kültür programını seç, çevresindeki duraklarla kendi gününü kur.</p></div><div><Link href="/walks">Şehir rotalarını keşfet ↗</Link><p>Program ve fiyatlar değişebilir. Gitmeden önce resmî kaynağı kontrol et.</p><p className="site-footer-note">KİŞİSEL PLANLAR BU TARAYICIDA SAKLANIR.</p></div></footer>
 </main>;
}
